spring.application.name=reservas-hotel
spring.mvc.problemdetails.enabled=true
reservas.demo.enabled=false
reservas.archivo=${RESERVAS_ARCHIVO:reservas.txt}
reservas.facturacion.nit=${RESERVAS_NIT:900123456-7}
